name: Go Build and Docker build-push

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.1'

      - name: Get tag
        id: branch_name
        run: echo ::set-env name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Test tag
        run: echo $SOURCE_TAG

      - name: Go Build
        run: go build

      - name: Login to GitHub Registry Container
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Create docker fdm-repository-backend image
        run: docker build -t ghcr.io/mattrighetti/fdm-repository-backend:$SOURCE_TAG .

      - name: Push docker images
        run: docker push ghcr.io/mattrighetti/fdm-repository-backend:$SOURCE_TAG