name: Go Build and Docker build-push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.1'

      - name: Set SHA8
        run: echo ::set-env name=SHA8::$(git log --oneline -1 | awk '{print $1}')

      - name: Go Build
        run: go build

      - name: Login to GitHub Registry Container
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Create docker fdm-repository-backend image
        run: docker build -t ghcr.io/mattrighetti/fdm-repository-backend:latest -t ghcr.io/mattrighetti/fdm-repository-backend:$SHA8 .

      - name: Push docker images
        run: |
          docker push ghcr.io/mattrighetti/fdm-repository-backend:latest
          docker push ghcr.io/mattrighetti/fdm-repository-backend:$SHA8